from django.utils.deprecation import MiddlewareMixin


TRANSLATION_MAP = {
    "hi": {
        "Dashboard": "डैशबोर्ड",
        "My Profile": "मेरी प्रोफाइल",
        "Logout": "लॉगआउट",
        "Login": "लॉगिन",
        "Create account": "अकाउंट बनाएं",
        "Language": "भाषा",
        "Welcome back": "वापसी पर स्वागत है",
        "Student Dashboard": "स्टूडेंट डैशबोर्ड",
        "Counsellor Dashboard": "काउंसलर डैशबोर्ड",
        "Admin Dashboard": "एडमिन डैशबोर्ड",
        "Open AI Chat Support": "AI चैट सपोर्ट खोलें",
        "Take Mental Health Assessment": "मेंटल हेल्थ असेसमेंट लें",
        "Book a session": "सेशन बुक करें",
        "Book counsellor": "काउंसलर बुक करें",
        "Take assessment": "असेसमेंट लें",
        "Export chat PDF": "चैट PDF एक्सपोर्ट करें",
        "Chat language": "चैट भाषा",
        "Send message": "मैसेज भेजें",
        "How this chat helps": "यह चैट कैसे मदद करती है",
        "Current risk status:": "वर्तमान जोखिम स्थिति:",
        "High": "उच्च",
        "Medium": "मध्यम",
        "Low": "निम्न",
        "Daily student posts": "दैनिक छात्र पोस्ट",
        "Create Post": "पोस्ट बनाएं",
        "Post your daily update": "अपना दैनिक अपडेट पोस्ट करें",
        "Photo (optional)": "फोटो (वैकल्पिक)",
        "Share post": "पोस्ट शेयर करें",
        "Student Feed": "स्टूडेंट फीड",
        "Latest posts": "नवीनतम पोस्ट",
        "No posts yet. Be the first to share today's check-in.": "अभी कोई पोस्ट नहीं है। आज का चेक-इन शेयर करने वाले पहले बनें।",
        "Community Check-in": "कम्युनिटी चेक-इन",
        "Quick Start": "क्विक स्टार्ट",
        "Featured Resources": "फीचर्ड संसाधन",
        "Wellness Tools": "वेलनेस टूल्स",
        "Recent check-ins": "हाल के चेक-इन",
        "System Analytics": "सिस्टम एनालिटिक्स",
        "Priority Queue": "प्राथमिकता कतार",
        "Your Daily Posts": "आपकी दैनिक पोस्ट",
        "Recent check-ins": "हाल के चेक-इन",
        "Quick daily post": "त्वरित दैनिक पोस्ट",
        "Write your check-in (optional if image uploaded)...": "अपना चेक-इन लिखें (यदि फोटो अपलोड है तो वैकल्पिक)...",
        "Photo / Camera (optional)": "फोटो / कैमरा (वैकल्पिक)",
        "Post now": "अभी पोस्ट करें",
        "Open full post feed": "पूरा पोस्ट फीड खोलें",
        "No daily check-in posted yet. Share your first update from the post feed.": "अभी तक कोई दैनिक चेक-इन पोस्ट नहीं हुआ। पोस्ट फीड से अपना पहला अपडेट साझा करें।",
        "Mental wellness platform for students": "छात्रों के लिए मानसिक स्वास्थ्य प्लेटफॉर्म",
        "Welcome back to Wellify": "वेलिफाई में आपका फिर से स्वागत है",
        "Secure Access": "सुरक्षित प्रवेश",
        "Email": "ईमेल",
        "Password": "पासवर्ड",
        "Login as": "लॉगिन प्रकार",
        "Select your role": "अपनी भूमिका चुनें",
        "Student": "छात्र",
        "Counsellor": "काउंसलर",
        "Admin": "एडमिन",
        "Create your Wellify account": "अपना वेलिफाई अकाउंट बनाएं",
        "Get Started": "शुरू करें",
        "Name": "नाम",
        "Role": "भूमिका",
        "Confirm password": "पासवर्ड की पुष्टि करें",
        "Back to login": "लॉगिन पर वापस जाएं",
        "AI Support": "एआई सहायता",
        "Wellify Chat Support": "वेलिफाई चैट सहायता",
        "Take Mental Health Assessment": "मानसिक स्वास्थ्य मूल्यांकन करें",
        "Community Check-in": "सामुदायिक चेक-इन",
        "Share your daily mood like a social update. Wellify auto-tags stress level so counsellors can prioritize support.": "सोशल अपडेट की तरह अपना दैनिक मूड साझा करें। वेलिफाई तनाव स्तर को स्वतः टैग करता है ताकि काउंसलर प्राथमिकता से सहायता दे सकें।",
        "What is on your mind today?": "आज आपके मन में क्या चल रहा है?",
        "Create Post": "पोस्ट बनाएं",
        "Write your daily check-in...": "अपना दैनिक चेक-इन लिखें...",
        "How it works": "यह कैसे काम करता है",
        "Smart support queue": "स्मार्ट सपोर्ट कतार",
        "Each post gets tagged as Low, Medium, or High stress signal.": "हर पोस्ट को निम्न, मध्यम या उच्च तनाव संकेत के रूप में टैग किया जाता है।",
        "Counsellor dashboard highlights higher-risk posts first.": "काउंसलर डैशबोर्ड पहले उच्च-जोखिम पोस्ट दिखाता है।",
        "Use this daily for early support, not only during crisis.": "सिर्फ संकट में नहीं, जल्दी सहायता के लिए इसे रोज़ इस्तेमाल करें।",
        "Student Dashboard": "स्टूडेंट डैशबोर्ड",
        "Your personal wellness hub is ready with guided tools, AI support, reflective journaling, and counsellor access whenever you need it.": "आपका व्यक्तिगत वेलनेस हब तैयार है, जहाँ गाइडेड टूल्स, AI सपोर्ट, जर्नलिंग और काउंसलर एक्सेस उपलब्ध है।",
        "Current wellbeing status:": "वर्तमान वेलबीइंग स्थिति:",
        "You're in a steady zone. Keep your momentum with short mindfulness breaks, daily reflection, and intentional rest.": "आप स्थिर स्थिति में हैं। छोटे माइंडफुलनेस ब्रेक, दैनिक चिंतन और सही आराम बनाए रखें।",
        "You're carrying some pressure right now. Breathing tools, a quick assessment, or a counselling booking can help you reset.": "आप इस समय दबाव महसूस कर रहे हैं। ब्रीदिंग टूल्स, एक क्विक असेसमेंट या काउंसलिंग बुकिंग मदद कर सकती है।",
        "Support has been prioritized for you. Stay close to grounding resources and reach out for human help as soon as possible.": "आपके लिए सहायता प्राथमिकता में रखी गई है। ग्राउंडिंग संसाधनों के साथ रहें और जल्दी मानव सहायता लें।",
        "Meditation sessions": "मेडिटेशन सेशन",
        "Breathing resources": "ब्रीदिंग संसाधन",
        "Motivational reads": "मोटिवेशनल सामग्री",
        "What would help most right now?": "अभी आपको सबसे ज्यादा किस चीज़ से मदद मिलेगी?",
        "Talk to Wellify AI": "वेलिफाई AI से बात करें",
        "Open your journal": "अपना जर्नल खोलें",
        "Reset with breathing": "ब्रीदिंग से रीसेट करें",
        "Check in with your mind": "अपने मन की स्थिति जांचें",
        "Choose the right tool": "सही टूल चुनें",
        "Escalate safely when needed": "ज़रूरत पड़ने पर सुरक्षित रूप से सहायता बढ़ाएँ",
        "Your 7-day assessment trend": "आपका 7-दिवसीय असेसमेंट ट्रेंड",
        "Latest student posts": "नवीनतम छात्र पोस्ट",
        "No public posts yet.": "अभी कोई सार्वजनिक पोस्ट नहीं है।",
        "Featured Resources": "चयनित संसाधन",
        "Recommended wellness content": "सुझाया गया वेलनेस कंटेंट",
        "Start session": "सेशन शुरू करें",
        "Practice now": "अभी अभ्यास करें",
        "Explore the full toolkit": "पूरा टूलकिट एक्सप्लोर करें",
        "Meditation library": "मेडिटेशन लाइब्रेरी",
        "Breathing exercises": "ब्रीदिंग एक्सरसाइज",
        "Personal journal": "व्यक्तिगत जर्नल",
        "Motivational content": "मोटिवेशनल कंटेंट",
        "Today's Boost": "आज का बूस्ट",
        "Small support, right on time": "छोटी मदद, सही समय पर",
        "Read more": "और पढ़ें",
        "Counsellor Workspace": "काउंसलर कार्यक्षेत्र",
        "Student risk and appointment overview": "छात्र जोखिम और अपॉइंटमेंट अवलोकन",
        "High-risk students": "उच्च जोखिम छात्र",
        "Medium-risk students": "मध्यम जोखिम छात्र",
        "Pending appointments": "लंबित अपॉइंटमेंट",
        "Immediate follow-up cases": "तुरंत फॉलो-अप केस",
        "Session active": "सेशन सक्रिय",
        "Needs scheduling": "शेड्यूलिंग आवश्यक",
        "Schedule session": "सेशन शेड्यूल करें",
        "Open chat history": "चैट हिस्ट्री खोलें",
        "Student posts needing review": "समीक्षा हेतु छात्र पोस्ट",
        "High Risk": "उच्च जोखिम",
        "Medium Risk": "मध्यम जोखिम",
        "Low Risk": "निम्न जोखिम",
        "Appointments": "अपॉइंटमेंट्स",
        "Session pipeline": "सेशन पाइपलाइन",
        "Approve": "स्वीकृत करें",
        "Mark completed": "पूर्ण चिह्नित करें",
        "Admin Command Center": "एडमिन कमांड सेंटर",
        "Institution wellness overview": "संस्थान वेलनेस अवलोकन",
        "Total users": "कुल उपयोगकर्ता",
        "Students": "छात्र",
        "Counsellors": "काउंसलर",
        "Admins": "एडमिन",
        "Total appointments": "कुल अपॉइंटमेंट्स",
        "System Analytics": "सिस्टम एनालिटिक्स",
        "Current institution picture": "संस्थान की वर्तमान स्थिति",
        "Manage users": "उपयोगकर्ता प्रबंधन",
        "Open reports": "रिपोर्ट खोलें",
        "Recent Activity": "हाल की गतिविधि",
        "Recent Accounts": "हाल के अकाउंट",
        "Newest users": "नवीनतम उपयोगकर्ता",
        "User Directory": "उपयोगकर्ता निर्देशिका",
        "Platform users": "प्लेटफ़ॉर्म उपयोगकर्ता",
        "Back to dashboard": "डैशबोर्ड पर वापस जाएँ",
        "Account Settings": "अकाउंट सेटिंग्स",
        "My profile": "मेरी प्रोफाइल",
        "Save changes": "परिवर्तन सहेजें",
        "Welcome back to Wellify": "वेलिफाई में आपका फिर से स्वागत है",
        "Sign in to continue your wellness journey, review support tools, and access your role-based dashboard.": "अपनी वेलनेस यात्रा जारी रखने, सपोर्ट टूल्स देखने और भूमिका-आधारित डैशबोर्ड खोलने के लिए लॉगिन करें।",
        "New here? Create your account to access assessments, guided support, and wellness resources.": "नए हैं? असेसमेंट, गाइडेड सपोर्ट और वेलनेस संसाधनों के लिए अकाउंट बनाएं।",
        "Quick Start": "क्विक स्टार्ट",
        "Community Feed": "कम्युनिटी फीड",
        "Featured Resources": "फीचर्ड रिसोर्सेस",
        "Recommended wellness content": "सुझाया गया वेलनेस कंटेंट",
        "Wellness Tools": "वेलनेस टूल्स",
        "Today's Boost": "आज का बूस्ट",
        "Small support, right on time": "छोटी मदद, सही समय पर",
        "Meditation": "मेडिटेशन",
        "Breathing": "ब्रीदिंग",
        "No users found.": "कोई उपयोगकर्ता नहीं मिला।",
        "No recent appointments available.": "हाल के अपॉइंटमेंट उपलब्ध नहीं हैं।",
        "No matching students for selected filter.": "चुने गए फ़िल्टर के लिए कोई छात्र नहीं मिला।",
        "High only": "केवल उच्च",
        "All students": "सभी छात्र",
        "Reports and Exports": "रिपोर्ट और एक्सपोर्ट",
        "Mental health and service analytics": "मेंटल हेल्थ और सर्विस एनालिटिक्स",
        "Export CSV": "CSV एक्सपोर्ट करें",
        "Export PDF": "PDF एक्सपोर्ट करें",
        "Assessment overview": "असेसमेंट अवलोकन",
        "Operational Metrics": "ऑपरेशनल मेट्रिक्स",
        "Session delivery": "सेशन डिलीवरी",
        "Visual Reports": "विज़ुअल रिपोर्ट्स",
        "Distribution snapshots": "डिस्ट्रीब्यूशन स्नैपशॉट्स",
        "Counsellor Performance": "काउंसलर प्रदर्शन",
        "Session counts by counsellor": "काउंसलर के अनुसार सेशन संख्या",
        "No counsellors found.": "कोई काउंसलर नहीं मिला।",
        "ERP and LMS": "ERP और LMS",
        "Institution data integration": "संस्थान डेटा इंटीग्रेशन",
        "Connection Status": "कनेक्शन स्थिति",
        "Disconnect integration": "इंटीग्रेशन डिस्कनेक्ट करें",
        "Connect integration": "इंटीग्रेशन कनेक्ट करें",
        "Import Rules": "इंपोर्ट नियम",
        "CSV format": "CSV फॉर्मेट",
        "Bulk Import": "बल्क इंपोर्ट",
        "Upload users from CSV": "CSV से उपयोगकर्ता अपलोड करें",
        "CSV file": "CSV फ़ाइल",
        "Upload and create users": "अपलोड करें और उपयोगकर्ता बनाएं",
        "Sample CSV": "सैंपल CSV",
        "Connect the integration first to enable CSV upload.": "CSV अपलोड सक्षम करने के लिए पहले इंटीग्रेशन कनेक्ट करें।",
        "User Record": "उपयोगकर्ता रिकॉर्ड",
        "Account role": "अकाउंट भूमिका",
        "Current stress level": "वर्तमान तनाव स्तर",
        "Latest assessment": "नवीनतम असेसमेंट",
        "Back to users": "उपयोगकर्ताओं पर वापस जाएँ",
        "User Directory": "यूज़र डायरेक्टरी",
        "Platform users": "प्लेटफॉर्म उपयोगकर्ता",
        "Counsellor Action": "काउंसलर एक्शन",
        "Schedule session for": "के लिए सेशन शेड्यूल करें",
        "Session date": "सेशन तिथि",
        "Student Chat Review": "स्टूडेंट चैट रिव्यू",
        "Review the conversation trail alongside the latest mental health signal before follow-up.": "फॉलो-अप से पहले नवीनतम मानसिक स्वास्थ्य संकेत के साथ बातचीत इतिहास देखें।",
        "Conversation history": "वार्तालाप इतिहास",
        "User": "यूज़र",
        "Current signal": "वर्तमान संकेत",
        "Stress level:": "तनाव स्तर:",
        "Assessment level:": "असेसमेंट स्तर:",
        "No assessment recorded yet.": "अभी कोई असेसमेंट दर्ज नहीं है।",
        "No chat history for this student.": "इस छात्र के लिए कोई चैट इतिहास नहीं है।",
        "Request a counselling session": "काउंसलिंग सेशन का अनुरोध करें",
        "Counselling Support": "काउंसलिंग सपोर्ट",
        "Choose a preferred date and we will route your request to an available counsellor for confirmation.": "अपनी पसंदीदा तिथि चुनें, हम आपकी रिक्वेस्ट उपलब्ध काउंसलर को भेज देंगे।",
        "Preferred date": "पसंदीदा तिथि",
        "Request appointment": "अपॉइंटमेंट अनुरोध करें",
        "Mindset Feed": "माइंडसेट फीड",
        "Daily inspiration and perspective": "दैनिक प्रेरणा और दृष्टिकोण",
        "Breathing Studio": "ब्रीदिंग स्टूडियो",
        "Guided breathing exercises": "गाइडेड ब्रीदिंग एक्सरसाइज",
        "Meditation Library": "मेडिटेशन लाइब्रेरी",
        "Guided meditation sessions": "गाइडेड मेडिटेशन सेशन",
        "Learn and practice": "सीखें और अभ्यास करें",
        "Start meditation": "मेडिटेशन शुरू करें",
        "No breathing exercises available yet. Run the wellness content population command to add guided exercises.": "अभी ब्रीदिंग एक्सरसाइज उपलब्ध नहीं हैं। गाइडेड एक्सरसाइज जोड़ने के लिए कंटेंट पॉपुलेशन कमांड चलाएं।",
        "No meditation guides available yet. Run the wellness content population command to add curated sessions.": "अभी मेडिटेशन गाइड उपलब्ध नहीं हैं। क्यूरेटेड सेशन जोड़ने के लिए कंटेंट पॉपुलेशन कमांड चलाएं।",
        "Secure Access": "सुरक्षित एक्सेस",
        "Get Started": "शुरू करें",
        "Login as": "लॉगिन प्रकार",
        "Select your role": "अपनी भूमिका चुनें",
        "Create account": "अकाउंट बनाएं",
        "Back to login": "लॉगिन पर वापस जाएँ",
        "Name": "नाम",
        "Email": "ईमेल",
        "Role": "भूमिका",
        "Password": "पासवर्ड",
        "Confirm password": "पासवर्ड पुष्टि करें",
        "Your personal wellness hub is ready with guided tools, AI support, reflective journaling, and counsellor access whenever you need it.": "आपका व्यक्तिगत वेलनेस हब गाइडेड टूल्स, एआई सपोर्ट, जर्नलिंग और काउंसलर एक्सेस के साथ तैयार है।",
        "Get contextual emotional support, practical coping ideas, and guidance to the right next step.": "भावनात्मक सहायता, व्यावहारिक उपाय और सही अगले कदम का मार्गदर्शन पाएं।",
        "Request time with a counsellor when you want structured, human support.": "जब आपको संरचित मानव सहायता चाहिए, तो काउंसलर के साथ समय बुक करें।",
        "Write through thoughts, capture moods, and keep your reflections in one place.": "अपने विचार लिखें, मूड रिकॉर्ड करें और अपनी रिफ्लेक्शन एक जगह रखें।",
        "Use short guided exercises to settle anxiety, improve focus, and regulate stress.": "चिंता कम करने, फोकस बेहतर करने और तनाव नियंत्रित करने के लिए छोटे गाइडेड अभ्यास करें।",
        "Share a daily update like social stories and get stress signals (Low/Medium/High).": "सोशल स्टोरी की तरह दैनिक अपडेट शेयर करें और तनाव संकेत (निम्न/मध्यम/उच्च) पाएं।",
        "Use PHQ-9 and GAD-7 assessments to understand your current emotional load and risk level.": "अपनी वर्तमान भावनात्मक स्थिति और जोखिम स्तर समझने के लिए PHQ-9 और GAD-7 असेसमेंट करें।",
        "Move between chat support, breathing exercises, meditations, journaling, and motivational content based on what you need.": "अपनी ज़रूरत के अनुसार चैट सपोर्ट, ब्रीदिंग, मेडिटेशन, जर्नलिंग और प्रेरक सामग्री के बीच जाएँ।",
        "High-risk patterns can trigger immediate recommendations and counsellor visibility for faster support.": "उच्च-जोखिम पैटर्न तुरंत सुझाव और काउंसलर विज़िबिलिटी ट्रिगर कर सकते हैं।",
        "Line shows your recent PHQ + GAD combined score snapshots. Higher score means you may need faster support.": "यह लाइन आपके हाल के PHQ + GAD संयुक्त स्कोर दिखाती है। अधिक स्कोर का मतलब है कि आपको जल्दी सहायता की जरूरत हो सकती है।",
        "(Image-only post)": "(केवल इमेज पोस्ट)",
        "Browse calming guided sessions for focus, sleep, and emotional regulation.": "फोकस, नींद और भावनात्मक संतुलन के लिए शांत गाइडेड सेशन देखें।",
        "Use evidence-based breathing patterns for panic, stress, and concentration support.": "पैनिक, तनाव और एकाग्रता के लिए वैज्ञानिक ब्रीदिंग पैटर्न अपनाएं।",
        "Capture daily mood, process feelings, and build awareness over time.": "दैनिक मूड रिकॉर्ड करें, भावनाएँ समझें और समय के साथ जागरूकता बढ़ाएँ।",
        "Read encouraging, recovery-oriented reflections when you need perspective.": "जब दृष्टिकोण की जरूरत हो, प्रेरक और रिकवरी-केंद्रित विचार पढ़ें।",
        "Motivational content will appear here once the wellness library is populated.": "वेलनेस लाइब्रेरी भरने के बाद यहाँ प्रेरक सामग्री दिखेगी।",
        "Wellify is typing...": "Wellify टाइप कर रहा है...",
        "Something went wrong. Please try again.": "कुछ गलत हुआ। कृपया फिर से प्रयास करें।",
        "Stress: ": "तनाव: ",
    },
    "gu": {
        "Dashboard": "ડેશબોર્ડ",
        "My Profile": "મારી પ્રોફાઇલ",
        "Logout": "લોગઆઉટ",
        "Login": "લૉગિન",
        "Create account": "એકાઉન્ટ બનાવો",
        "Language": "ભાષા",
        "Welcome back": "પાછા આવવા બદલ સ્વાગત",
        "Student Dashboard": "વિદ્યાર્થી ડેશબોર્ડ",
        "Counsellor Dashboard": "કાઉન્સેલર ડેશબોર્ડ",
        "Admin Dashboard": "એડમિન ડેશબોર્ડ",
        "Open AI Chat Support": "AI ચેટ સપોર્ટ ખોલો",
        "Take Mental Health Assessment": "મેન્ટલ હેલ્થ મૂલ્યાંકન લો",
        "Book a session": "સેશન બુક કરો",
        "Book counsellor": "કાઉન્સેલર બુક કરો",
        "Take assessment": "મૂલ્યાંકન લો",
        "Export chat PDF": "ચેટ PDF એક્સપોર્ટ કરો",
        "Chat language": "ચેટ ભાષા",
        "Send message": "મેસેજ મોકલો",
        "How this chat helps": "આ ચેટ કેવી રીતે મદદ કરે છે",
        "Current risk status:": "હાલની જોખમ સ્થિતિ:",
        "High": "ઉચ્ચ",
        "Medium": "મધ્યમ",
        "Low": "નિમ્ન",
        "Daily student posts": "દૈનિક વિદ્યાર્થી પોસ્ટ્સ",
        "Create Post": "પોસ્ટ બનાવો",
        "Post your daily update": "તમારું દૈનિક અપડેટ પોસ્ટ કરો",
        "Photo (optional)": "ફોટો (વૈકલ્પિક)",
        "Share post": "પોસ્ટ શેર કરો",
        "Student Feed": "વિદ્યાર્થી ફીડ",
        "Latest posts": "નવીનતમ પોસ્ટ્સ",
        "No posts yet. Be the first to share today's check-in.": "હજુ સુધી કોઈ પોસ્ટ નથી. આજે ચેક-ઇન શેર કરનાર પ્રથમ બનો.",
        "Community Check-in": "સમુદાય ચેક-ઇન",
        "Quick Start": "ક્વિક સ્ટાર્ટ",
        "Featured Resources": "ફીચર્ડ સ્રોતો",
        "Wellness Tools": "વેલનેસ ટૂલ્સ",
        "Recent check-ins": "તાજેતરના ચેક-ઇન",
        "System Analytics": "સિસ્ટમ એનાલિટિક્સ",
        "Priority Queue": "પ્રાથમિકતા કતાર",
        "Your Daily Posts": "તમારી દૈનિક પોસ્ટ્સ",
        "Recent check-ins": "તાજેતરના ચેક-ઇન",
        "Quick daily post": "ઝડપી દૈનિક પોસ્ટ",
        "Write your check-in (optional if image uploaded)...": "તમારો ચેક-ઇન લખો (ફોટો અપલોડ કરેલ હોય તો વૈકલ્પિક)...",
        "Photo / Camera (optional)": "ફોટો / કેમેરા (વૈકલ્પિક)",
        "Post now": "હમણાં પોસ્ટ કરો",
        "Open full post feed": "પૂર્ણ પોસ્ટ ફીડ ખોલો",
        "No daily check-in posted yet. Share your first update from the post feed.": "હજુ સુધી કોઈ દૈનિક ચેક-ઇન પોસ્ટ નથી. પોસ્ટ ફીડમાંથી તમારું પ્રથમ અપડેટ શેર કરો.",
        "Mental wellness platform for students": "વિદ્યાર્થીઓ માટે માનસિક સ્વાસ્થ્ય પ્લેટફોર્મ",
        "Welcome back to Wellify": "વેલિફાયમાં ફરીથી સ્વાગત છે",
        "Secure Access": "સુરક્ષિત પ્રવેશ",
        "Email": "ઈમેલ",
        "Password": "પાસવર્ડ",
        "Login as": "લૉગિન તરીકે",
        "Select your role": "તમારી ભૂમિકા પસંદ કરો",
        "Student": "વિદ્યાર્થી",
        "Counsellor": "કાઉન્સેલર",
        "Admin": "એડમિન",
        "Create your Wellify account": "તમારું વેલિફાય અકાઉન્ટ બનાવો",
        "Get Started": "શરૂ કરો",
        "Name": "નામ",
        "Role": "ભૂમિકા",
        "Confirm password": "પાસવર્ડની પુષ્ટિ કરો",
        "Back to login": "લૉગિન પર પાછા જાઓ",
        "AI Support": "AI સપોર્ટ",
        "Wellify Chat Support": "વેલિફાય ચેટ સપોર્ટ",
        "Take Mental Health Assessment": "માનસિક સ્વાસ્થ્ય મૂલ્યાંકન લો",
        "Community Check-in": "સમુદાય ચેક-ઇન",
        "Share your daily mood like a social update. Wellify auto-tags stress level so counsellors can prioritize support.": "સોશિયલ અપડેટની જેમ તમારું દૈનિક મૂડ શેર કરો. વેલિફાય સ્ટ્રેસ લેવલને ઓટો-ટેગ કરે છે જેથી કાઉન્સેલર પ્રાથમિકતા આપી શકે.",
        "What is on your mind today?": "આજે તમારા મનમાં શું ચાલી રહ્યું છે?",
        "Create Post": "પોસ્ટ બનાવો",
        "Write your daily check-in...": "તમારું દૈનિક ચેક-ઇન લખો...",
        "How it works": "આ કેવી રીતે કામ કરે છે",
        "Smart support queue": "સ્માર્ટ સપોર્ટ કતાર",
        "Each post gets tagged as Low, Medium, or High stress signal.": "દરેક પોસ્ટને નીચા, મધ્યમ અથવા ઉચ્ચ સ્ટ્રેસ સિગ્નલ તરીકે ટૅગ કરવામાં આવે છે.",
        "Counsellor dashboard highlights higher-risk posts first.": "કાઉન્સેલર ડેશબોર્ડ સૌથી પહેલા ઉચ્ચ જોખમ પોસ્ટ્સ બતાવે છે.",
        "Use this daily for early support, not only during crisis.": "માત્ર સંકટમાં નહીં, વહેલી મદદ માટે દરરોજ તેનો ઉપયોગ કરો.",
        "Student Dashboard": "વિદ્યાર્થી ડેશબોર્ડ",
        "Your personal wellness hub is ready with guided tools, AI support, reflective journaling, and counsellor access whenever you need it.": "તમારો વ્યક્તિગત વેલનેસ હબ તૈયાર છે, જેમાં માર્ગદર્શિત ટૂલ્સ, AI સપોર્ટ, જર્નલિંગ અને કાઉન્સેલર ઍક્સેસ ઉપલબ્ધ છે.",
        "Current wellbeing status:": "હાલની સુખાકારી સ્થિતિ:",
        "You're in a steady zone. Keep your momentum with short mindfulness breaks, daily reflection, and intentional rest.": "તમે સ્થિર સ્થિતિમાં છો. નાની માઇન્ડફુલનેસ બ્રેક્સ, દૈનિક પ્રતિબિંબ અને યોગ્ય આરામ જાળવો.",
        "You're carrying some pressure right now. Breathing tools, a quick assessment, or a counselling booking can help you reset.": "તમે હાલમાં દબાણ અનુભવો છો. બ્રેધિંગ ટૂલ્સ, ક્વિક મૂલ્યાંકન અથવા કાઉન્સેલિંગ બુકિંગ તમને રીસેટ કરવામાં મદદ કરશે.",
        "Support has been prioritized for you. Stay close to grounding resources and reach out for human help as soon as possible.": "તમારા માટે સહાયને પ્રાથમિકતા આપવામાં આવી છે. ગ્રાઉન્ડિંગ સ્રોતો નજીક રાખો અને માનવીય મદદ માટે વહેલી તકે સંપર્ક કરો.",
        "Meditation sessions": "મેડિટેશન સેશન",
        "Breathing resources": "બ્રેધિંગ સ્રોતો",
        "Motivational reads": "મોટિવેશનલ વાંચન",
        "What would help most right now?": "હમણાં તમને સૌથી વધુ કઈ મદદ જરૂરી છે?",
        "Talk to Wellify AI": "વેલિફાય AI સાથે વાત કરો",
        "Open your journal": "તમારું જર્નલ ખોલો",
        "Reset with breathing": "બ્રેધિંગથી રીસેટ કરો",
        "Check in with your mind": "તમારા મનની સ્થિતિ તપાસો",
        "Choose the right tool": "યોગ્ય ટૂલ પસંદ કરો",
        "Escalate safely when needed": "જરૂર પડે ત્યારે સુરક્ષિત રીતે સહાય વધારો",
        "Your 7-day assessment trend": "તમારો 7-દિવસીય મૂલ્યાંકન ટ્રેન્ડ",
        "Latest student posts": "નવીનતમ વિદ્યાર્થી પોસ્ટ્સ",
        "No public posts yet.": "હજુ સુધી કોઈ જાહેર પોસ્ટ નથી.",
        "Featured Resources": "ફીચર્ડ સ્રોતો",
        "Recommended wellness content": "ભલામણ કરાયેલ વેલનેસ સામગ્રી",
        "Start session": "સેશન શરૂ કરો",
        "Practice now": "હમણાં પ્રેક્ટિસ કરો",
        "Explore the full toolkit": "પૂર્ણ ટૂલકિટ શોધો",
        "Meditation library": "મેડિટેશન લાઇબ્રેરી",
        "Breathing exercises": "બ્રેધિંગ વ્યાયામ",
        "Personal journal": "વ્યક્તિગત જર્નલ",
        "Motivational content": "મોટિવેશનલ સામગ્રી",
        "Today's Boost": "આજનો બૂસ્ટ",
        "Small support, right on time": "નાની મદદ, યોગ્ય સમયે",
        "Read more": "વધુ વાંચો",
        "Counsellor Workspace": "કાઉન્સેલર વર્કસ્પેસ",
        "Student risk and appointment overview": "વિદ્યાર્થી જોખમ અને એપોઇન્ટમેન્ટ અવલોકન",
        "High-risk students": "ઉચ્ચ જોખમ વિદ્યાર્થીઓ",
        "Medium-risk students": "મધ્યમ જોખમ વિદ્યાર્થીઓ",
        "Pending appointments": "લંબિત એપોઇન્ટમેન્ટ્સ",
        "Immediate follow-up cases": "તાત્કાલિક ફોલો-અપ કેસ",
        "Session active": "સેશન સક્રિય",
        "Needs scheduling": "શેડ્યૂલિંગ જરૂરી",
        "Schedule session": "સેશન શેડ્યૂલ કરો",
        "Open chat history": "ચેટ ઇતિહાસ ખોલો",
        "Student posts needing review": "સમીક્ષા માટે વિદ્યાર્થી પોસ્ટ્સ",
        "High Risk": "ઉચ્ચ જોખમ",
        "Medium Risk": "મધ્યમ જોખમ",
        "Low Risk": "નિમ્ન જોખમ",
        "Appointments": "એપોઇન્ટમેન્ટ્સ",
        "Session pipeline": "સેશન પાઇપલાઇન",
        "Approve": "મંજૂર કરો",
        "Mark completed": "પૂર્ણ તરીકે ચિહ્નિત કરો",
        "Admin Command Center": "એડમિન કમાન્ડ સેન્ટર",
        "Institution wellness overview": "સંસ્થાકીય વેલનેસ અવલોકન",
        "Total users": "કુલ યુઝર્સ",
        "Students": "વિદ્યાર્થીઓ",
        "Counsellors": "કાઉન્સેલર્સ",
        "Admins": "એડમિન",
        "Total appointments": "કુલ એપોઇન્ટમેન્ટ્સ",
        "System Analytics": "સિસ્ટમ એનાલિટિક્સ",
        "Current institution picture": "સંસ્થાની વર્તમાન સ્થિતિ",
        "Manage users": "યુઝર મેનેજ કરો",
        "Open reports": "રિપોર્ટ ખોલો",
        "Recent Activity": "તાજેતરની પ્રવૃત્તિ",
        "Recent Accounts": "તાજેતરના અકાઉન્ટ્સ",
        "Newest users": "નવીનતમ યુઝર્સ",
        "User Directory": "યુઝર ડિરેક્ટરી",
        "Platform users": "પ્લેટફોર્મ યુઝર્સ",
        "Back to dashboard": "ડેશબોર્ડ પર પાછા જાઓ",
        "Account Settings": "અકાઉન્ટ સેટિંગ્સ",
        "My profile": "મારી પ્રોફાઇલ",
        "Save changes": "ફેરફારો સાચવો",
        "Welcome back to Wellify": "વેલિફાયમાં ફરીથી સ્વાગત છે",
        "Sign in to continue your wellness journey, review support tools, and access your role-based dashboard.": "તમારી વેલનેસ યાત્રા ચાલુ રાખવા, સપોર્ટ ટૂલ્સ જોવા અને રોલ આધારિત ડેશબોર્ડ ઍક્સેસ કરવા સાઇન ઇન કરો.",
        "New here? Create your account to access assessments, guided support, and wellness resources.": "નવા છો? મૂલ્યાંકન, માર્ગદર્શિત સહાય અને વેલનેસ સ્રોતો મેળવવા અકાઉન્ટ બનાવો.",
        "Quick Start": "ઝડપી શરૂઆત",
        "Community Feed": "સમુદાય ફીડ",
        "Featured Resources": "ફીચર્ડ સ્રોતો",
        "Recommended wellness content": "ભલામણ કરાયેલ વેલનેસ સામગ્રી",
        "Wellness Tools": "વેલનેસ ટૂલ્સ",
        "Today's Boost": "આજનો બૂસ્ટ",
        "Small support, right on time": "નાની સહાય, યોગ્ય સમયે",
        "Meditation": "મેડિટેશન",
        "Breathing": "બ્રેધિંગ",
        "No users found.": "કોઈ યુઝર્સ મળ્યા નથી.",
        "No recent appointments available.": "તાજેતરના એપોઇન્ટમેન્ટ ઉપલબ્ધ નથી.",
        "No matching students for selected filter.": "પસંદ કરેલા ફિલ્ટર માટે મેળ ખાતા વિદ્યાર્થીઓ નથી.",
        "High only": "ફક્ત ઉચ્ચ",
        "All students": "બધા વિદ્યાર્થીઓ",
        "Reports and Exports": "રિપોર્ટ અને એક્સપોર્ટ",
        "Mental health and service analytics": "માનસિક સ્વાસ્થ્ય અને સેવા એનાલિટિક્સ",
        "Export CSV": "CSV એક્સપોર્ટ કરો",
        "Export PDF": "PDF એક્સપોર્ટ કરો",
        "Assessment overview": "મૂલ્યાંકન અવલોકન",
        "Operational Metrics": "ઓપરેશનલ મેટ્રિક્સ",
        "Session delivery": "સેશન ડિલિવરી",
        "Visual Reports": "વિઝ્યુઅલ રિપોર્ટ્સ",
        "Distribution snapshots": "ડિસ્ટ્રિબ્યુશન સ્નેપશોટ્સ",
        "Counsellor Performance": "કાઉન્સેલર પરફોર્મન્સ",
        "Session counts by counsellor": "કાઉન્સેલર મુજબ સેશન સંખ્યા",
        "No counsellors found.": "કોઈ કાઉન્સેલર મળ્યા નથી.",
        "ERP and LMS": "ERP અને LMS",
        "Institution data integration": "સંસ્થાગત ડેટા ઇન્ટિગ્રેશન",
        "Connection Status": "કનેક્શન સ્થિતિ",
        "Disconnect integration": "ઇન્ટિગ્રેશન ડિસકનેક્ટ કરો",
        "Connect integration": "ઇન્ટિગ્રેશન કનેક્ટ કરો",
        "Import Rules": "ઇમ્પોર્ટ નિયમો",
        "CSV format": "CSV ફોર્મેટ",
        "Bulk Import": "બલ્ક ઇમ્પોર્ટ",
        "Upload users from CSV": "CSV માંથી યુઝર્સ અપલોડ કરો",
        "CSV file": "CSV ફાઇલ",
        "Upload and create users": "અપલોડ કરો અને યુઝર્સ બનાવો",
        "Sample CSV": "સેમ્પલ CSV",
        "Connect the integration first to enable CSV upload.": "CSV અપલોડ માટે પહેલા ઇન્ટિગ્રેશન કનેક્ટ કરો.",
        "User Record": "યુઝર રેકોર્ડ",
        "Account role": "અકાઉન્ટ ભૂમિકા",
        "Current stress level": "હાલનો સ્ટ્રેસ લેવલ",
        "Latest assessment": "નવીનતમ મૂલ્યાંકન",
        "Back to users": "યુઝર્સ પર પાછા જાઓ",
        "User Directory": "યુઝર ડિરેક્ટરી",
        "Platform users": "પ્લેટફોર્મ યુઝર્સ",
        "Counsellor Action": "કાઉન્સેલર એક્શન",
        "Schedule session for": "માટે સેશન શેડ્યૂલ કરો",
        "Session date": "સેશન તારીખ",
        "Student Chat Review": "વિદ્યાર્થી ચેટ સમીક્ષા",
        "Review the conversation trail alongside the latest mental health signal before follow-up.": "ફોલો-અપ પહેલાં તાજા માનસિક સ્વાસ્થ્ય સંકેત સાથે વાતચીત ઇતિહાસ સમીક્ષા કરો.",
        "Conversation history": "વાતચીત ઇતિહાસ",
        "User": "યુઝર",
        "Current signal": "હાલનો સંકેત",
        "Stress level:": "સ્ટ્રેસ લેવલ:",
        "Assessment level:": "મૂલ્યાંકન લેવલ:",
        "No assessment recorded yet.": "હજુ સુધી કોઈ મૂલ્યાંકન નોંધાયેલ નથી.",
        "No chat history for this student.": "આ વિદ્યાર્થી માટે ચેટ ઇતિહાસ નથી.",
        "Request a counselling session": "કાઉન્સેલિંગ સેશન માટે વિનંતી કરો",
        "Counselling Support": "કાઉન્સેલિંગ સપોર્ટ",
        "Choose a preferred date and we will route your request to an available counsellor for confirmation.": "પસંદ તારીખ પસંદ કરો, અમે તમારી વિનંતી ઉપલબ્ધ કાઉન્સેલર સુધી પહોંચાડશું.",
        "Preferred date": "પસંદ તારીખ",
        "Request appointment": "એપોઇન્ટમેન્ટ વિનંતી કરો",
        "Mindset Feed": "માઇન્ડસેટ ફીડ",
        "Daily inspiration and perspective": "દૈનિક પ્રેરણા અને દૃષ્ટિકોણ",
        "Breathing Studio": "બ્રેધિંગ સ્ટુડિયો",
        "Guided breathing exercises": "માર્ગદર્શિત બ્રેધિંગ વ્યાયામ",
        "Meditation Library": "મેડિટેશન લાઇબ્રેરી",
        "Guided meditation sessions": "માર્ગદર્શિત મેડિટેશન સેશન્સ",
        "Learn and practice": "શીખો અને પ્રેક્ટિસ કરો",
        "Start meditation": "મેડિટેશન શરૂ કરો",
        "No breathing exercises available yet. Run the wellness content population command to add guided exercises.": "હજુ બ્રેધિંગ વ્યાયામ ઉપલબ્ધ નથી. માર્ગદર્શિત વ્યાયામ માટે કન્ટેન્ટ પોપ્યુલેશન કમાન્ડ ચલાવો.",
        "No meditation guides available yet. Run the wellness content population command to add curated sessions.": "હજુ મેડિટેશન ગાઇડ ઉપલબ્ધ નથી. ક્યુરેટેડ સેશન ઉમેરવા કન્ટેન્ટ પોપ્યુલેશન કમાન્ડ ચલાવો.",
        "Secure Access": "સુરક્ષિત પ્રવેશ",
        "Get Started": "શરૂ કરો",
        "Login as": "લૉગિન તરીકે",
        "Select your role": "તમારી ભૂમિકા પસંદ કરો",
        "Create account": "અકાઉન્ટ બનાવો",
        "Back to login": "લૉગિન પર પાછા જાઓ",
        "Name": "નામ",
        "Email": "ઈમેલ",
        "Role": "ભૂમિકા",
        "Password": "પાસવર્ડ",
        "Confirm password": "પાસવર્ડની પુષ્ટિ કરો",
        "Your personal wellness hub is ready with guided tools, AI support, reflective journaling, and counsellor access whenever you need it.": "તમારો વ્યક્તિગત વેલનેસ હબ માર્ગદર્શિત ટૂલ્સ, AI સપોર્ટ, જર્નલિંગ અને કાઉન્સેલર ઍક્સેસ સાથે તૈયાર છે.",
        "Get contextual emotional support, practical coping ideas, and guidance to the right next step.": "પ્રસંગોપાત ભાવનાત્મક સહાય, વ્યવહારૂ ઉપાયો અને યોગ્ય આગળના પગલાં માટે માર્ગદર્શન મેળવો.",
        "Request time with a counsellor when you want structured, human support.": "જ્યારે તમને ગોઠવેલ માનવીય સહાય જોઈએ ત્યારે કાઉન્સેલર સાથે સમય બુક કરો.",
        "Write through thoughts, capture moods, and keep your reflections in one place.": "વિચારો લખો, મૂડ નોંધો અને પ્રતિબિંબોને એક જગ્યાએ રાખો.",
        "Use short guided exercises to settle anxiety, improve focus, and regulate stress.": "ચિંતા શાંત કરવા, ફોકસ સુધારવા અને સ્ટ્રેસ નિયંત્રિત કરવા ટૂંકા માર્ગદર્શિત અભ્યાસ કરો.",
        "Share a daily update like social stories and get stress signals (Low/Medium/High).": "સોશિયલ સ્ટોરી જેવી દૈનિક અપડેટ શેર કરો અને સ્ટ્રેસ સિગ્નલ (નિમ્ન/મધ્યમ/ઉચ્ચ) મેળવો.",
        "Use PHQ-9 and GAD-7 assessments to understand your current emotional load and risk level.": "તમારી વર્તમાન ભાવનાત્મક સ્થિતિ અને જોખમ સ્તર સમજવા માટે PHQ-9 અને GAD-7 મૂલ્યાંકન કરો.",
        "Move between chat support, breathing exercises, meditations, journaling, and motivational content based on what you need.": "તમારી જરૂરિયાત મુજબ ચેટ સપોર્ટ, બ્રેધિંગ, મેડિટેશન, જર્નલિંગ અને પ્રેરણાત્મક સામગ્રી વચ્ચે ફેરફાર કરો.",
        "High-risk patterns can trigger immediate recommendations and counsellor visibility for faster support.": "ઉચ્ચ જોખમ પેટર્ન તાત્કાલિક ભલામણ અને કાઉન્સેલર વિઝિબિલિટી ટ્રિગર કરી શકે છે.",
        "Line shows your recent PHQ + GAD combined score snapshots. Higher score means you may need faster support.": "આ લાઇન તમારા તાજેતરના PHQ + GAD સંયુક્ત સ્કોર દર્શાવે છે. વધારે સ્કોર એટલે તમને ઝડપી સહાયની જરૂર હોઈ શકે છે.",
        "(Image-only post)": "(ફક્ત ઇમેજ પોસ્ટ)",
        "Browse calming guided sessions for focus, sleep, and emotional regulation.": "ફોકસ, ઊંઘ અને ભાવનાત્મક સંતુલન માટે શાંતિસભર માર્ગદર્શિત સેશન્સ જુઓ.",
        "Use evidence-based breathing patterns for panic, stress, and concentration support.": "પેનિક, સ્ટ્રેસ અને એકાગ્રતા માટે વૈજ્ઞાનિક બ્રેધિંગ પેટર્ન અપનાવો.",
        "Capture daily mood, process feelings, and build awareness over time.": "દૈનિક મૂડ કૅપ્ચર કરો, લાગણીઓ સમજો અને સમય સાથે જાગરૂકતા વધારો.",
        "Read encouraging, recovery-oriented reflections when you need perspective.": "જ્યારે દૃષ્ટિકોણની જરૂર હોય ત્યારે પ્રેરક અને પુનઃપ્રાપ્તિ-કેન્દ્રિત વિચાર વાંચો.",
        "Motivational content will appear here once the wellness library is populated.": "વેલનેસ લાઇબ્રેરી ભરાયા પછી અહીં પ્રેરણાત્મક સામગ્રી દેખાશે.",
        "Wellify is typing...": "Wellify ટાઇપ કરી રહ્યું છે...",
        "Something went wrong. Please try again.": "કઈંક ખોટું થયું. કૃપા કરીને ફરી પ્રયાસ કરો.",
        "Stress: ": "સ્ટ્રેસ: ",
    },
}


class GlobalUITextMiddleware(MiddlewareMixin):
    """Simple global text replacement for selected UI strings."""

    def process_response(self, request, response):
        content_type = response.get("Content-Type", "")
        if "text/html" not in content_type:
            return response

        lang = (request.session.get("django_language") or "en").strip().lower()
        lang_map = TRANSLATION_MAP.get(lang)
        if not lang_map:
            return response

        try:
            html = response.content.decode(response.charset or "utf-8")
        except Exception:
            return response

        # Replace longer phrases first so short tokens don't break matches.
        for source_text, translated_text in sorted(
            lang_map.items(), key=lambda item: len(item[0]), reverse=True
        ):
            html = html.replace(source_text, translated_text)

        response.content = html.encode(response.charset or "utf-8")
        return response
