# Generated by Django 4.2.28 on 2026-02-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_stress_level',
            field=models.CharField(default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_flagged_high',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
